// clients/ng-rest-client/src/app/shared/components/image/image.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { ImageSize } from './image-size';
import { environment } from '../../../../environments/environment';

@Component({
  selector: 'es-image',
  styleUrls: ['./image.component.css'],
  template: `
    <img
      [src]="url"
      [alt]="name"
      [ngStyle]="{
        width: width + 'px',
        height: height + 'px'
      }">
  `
})
export class ImageComponent implements OnInit {
  @Input() name: string;
  @Input() size: ImageSize;

  url: string = null;
  width = 200;
  height = 150;

  public ngOnInit(): void {
    this.setImageSize();
    this.url = `${environment.imageProxyUrl}/insecure/rs:fit:${this.width}:${this.height}:no:0/plain/s3://catalog-images/${this.name}`;
  }

  private setImageSize(): void {
    if (!this.size || this.size === ImageSize.Medium) {
      this.width = 240;
      this.height = 150;
    } else if (this.size === ImageSize.Small) {
      this.width = 40;
      this.height = 40;
    }
  }

}

// clients/react-graphql-client/src/shared/components/image/Image.tsx
import { ImageSize } from './ImageSize';
import { useEffect, useState } from 'react';

interface Props {
  name: string;
  size?: ImageSize;
}

interface Size {
  width: number;
  height: number;
}

const SIZE_MEDIUM: Size = {width: 240, height: 150};
const SIZE_SMALL: Size = {width: 40, height: 40};
const PLACEHOLDER = 'placeholder.png';

export const Image = (props: Props) => {
  const [size, setSize] = useState<Size>(SIZE_MEDIUM);
  const [src, setSrc] = useState<string>();

  useEffect(() => {
    if (props.size === ImageSize.Medium) {
      setSize(SIZE_MEDIUM)
    } else if (props.size === ImageSize.Small) {
      setSize(SIZE_SMALL);
    }
  }, [props.size]);

  useEffect(() => {
    setSrc(`${process.env.REACT_APP_IMAGE_SERVER_URL}/insecure/rs:fit:${size.width}:${size.height}:no:0/plain/s3://catalog-images/${props.name}`);
  }, [size, props.name]);

  const setPlaceholder = () => {
    setSrc(PLACEHOLDER);
  };

  return (
    <img
      src={src}
      alt={props.name}
      style={{
        width: size.width,
        height: size.height
      }}
      onError={setPlaceholder}
    />
  );
};
